# Configurations
title:            Jekyll Gitbook Template
longtitle:        Jekyll Gitbook Template
author:           Benito Zaragozí
email:            benizar@gmail.com
description: >
  Build Jekyll site with the GitBook style and Jekyll scholar.

version:          1.0
gitbook_version:  3.2.3

url:              'https://benizar.github.io'
baseurl:          '/jekyll-gitbook-template'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:name.html

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts
  - contrib
  - LICENSE
  - Makefile
  - README.md

collections:
  chapters:
    output: true
    permalink: /:collection/:name.html  # Generates clean URLs like /chapter-1.html
    sort_by: weight  # Enables manual ordering with 'weight'
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
  slides:
    output: true
    permalink: /:collection/:name.html  # Generates clean URLs like /slides/chapter-1.html
    
ordered_collections:
  - chapters
  - pages
  - others

reveal:
  theme: "black"  # Options: beige, blood, league, moon, night, serif, simple, sky, solarized, white
  transition: "slide"  # Options: none, fade, slide, convex, concave, zoom

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  
scholar:
  style: _bibliography/my-apa-cv-no-access.csl
  locale: en

  sort_by: year
  order: descending

  source: _bibliography
  bibliography: gis
  bibliography_template: bibliography

  replace_strings: true

  query: "@*"

