@startfiles
/LINEAS_LIMITE_GML.ZIP/
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeBoundary_1stOrder0.gml
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeBoundary_2ndOrder0.gml
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeBoundary_3rdOrder0.gml
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeBoundary_4thOrder0.gml
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeBoundary_4thOrder10000.gml
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeBoundary_4thOrder20000.gml
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeBoundary_4thOrder30000.gml
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeUnit_1stOrder0.gml
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeUnit_2ndOrder0.gml
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeUnit_3rdOrder0.gml
/LINEAS_LIMITE_GML.ZIP/au_AdministrativeUnit_4thOrder0.gml
/LINEAS_LIMITE_GML.ZIP/readme.txt
@endfiles
