block
  columns 2
  geometry["Geometria"]:2
  individual["Individual"]
  collection["Col·lecció"]
  point["Punt"]
  multipoint["Multipunt"]
  curve["Corba<br/>→ línia"]
  multicurve["Multicorba<br/>→ multilínia"]
  surface["Superfície<br/>→ polígon"]
  multisurface["Multisuperfície<br/>→ multipolígon"]
  geometry --> individual
  geometry --> collection
  individual --> point
  individual --> curve
  individual --> surface
  collection --> multipoint
  collection --> multicurve
  collection --> multisurface
