block
  columns 1
  clip["Retall<br/>geom.: A ∩ B<br/>atrib.: camps d'A"]
  intersection["Intersecció<br/>geom.: A ∩ B<br/>atrib.: camps d'A + B"]
  union["Unió*<br/>geom.: A ∪ B segmentat<br/>atrib.: A + B amb nuls"]
  difference["Diferència<br/>geom.: A − B<br/>atrib.: camps d'A"]
  dissolve["Dissolució<br/>geom.: unió per grup<br/>atrib.: cap resum implícit"]
  legend["A: entrada · B: segona entrada<br/>* Partició només sense solapaments interns"]
