@startfiles
/tig/
/tig/README.md
/tig/data/
/tig/data/raw/
/tig/data/processed/
/tig/data/processed/dem-area-merged.tif
/tig/data/interim/
/tig/sandbox/
/tig/sandbox/pr1-project-setup-cognom.gpkg
/tig/sandbox/pr1-project-setup-cognom.qgz
/tig/dist/
/tig/dist/pr1-project-setup-cognom.gpkg
/tig/dist/pr1-project-setup-cognom.qgz
/tig/dist/pr1-project-setup-cognom.pdf
/tig/diari.pdf
@endfiles
